name: Build MacOS
run-name: "Build MacOS"

on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: macos-14
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install general dependencies
        run: brew install automake make libtool miniupnpc protobuf qrencode librsvg python-setuptools
      - name: Build depends
        run: cd depends && make && cd ..
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --prefix=$PWD/depends/arm-apple-darwin23.6.0
      - name: Make
        run: |
          make
          make deploy
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MacOS arm64
          path: ./pocketcoind
