name: Build MacOS
run-name: "Build MacOS"

on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: macos-14
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install general dependencies
        run: brew install automake make libtool miniupnpc protobuf qrencode librsvg python-setuptools          
      - name: Build depends
        run: cd depends && make && cd ..
      - name: Install bdb4
        run: CFLAGS=-Wno-error=implicit-function-declaration ./contrib/install_db4.sh .
      - name: Configure
        run: |
          export LDFLAGS="-L/opt/homebrew/opt/openssl/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/openssl/include"
          ./autogen.sh
          ./configure --prefix=$PWD/depends/arm-apple-darwin23.6.0
      - name: Make
        run: |
          make
          make deploy
          
